apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-huj7
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0026-tenant/tkrw-pr712-0075-0026-app/devfile-sample-huj7@sha256:929edcbdb42e51a322e0b0e9d50a1c65a5aa653a02904412fa163ffaafa07652
        name: my-nodejs
        resources: {}
status: {}
