apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-huj7
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-huj7
    app.kubernetes.io/part-of: tkrw-pr712-0075-0026-app
  name: devfile-sample-huj7
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-huj7
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-huj7
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0026-tenant/tkrw-pr712-0075-0026-app/devfile-sample-huj7@sha256:929edcbdb42e51a322e0b0e9d50a1c65a5aa653a02904412fa163ffaafa07652
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
